version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/usr/app
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb